//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaco
    {
        public int Id { get; set; }
        public Nullable<int> ContaId { get; set; }
        public Nullable<int> TipoTransacaoId { get; set; }
        public double Valor { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Conta Conta { get; set; }
        public virtual TipoTransaco TipoTransaco { get; set; }
    }
}
